apiVersion: apps/v1
kind: Deployment
metadata:
  name: noted-flask
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: noted-flask
  template:
    metadata:
      labels:
        app: noted-flask
    spec:
      containers:
      - image: docker.io/debuglachy/noted-flask-app:46aa5cd7609317ad17356744a55fc6a4a251a3e7
        name: noted-flask
        ports:
        - containerPort: 8080
