apiVersion: apps/v1
kind: Deployment
metadata:
  name: noted-flask
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: noted-flask
  template:
    metadata:
      labels:
        app: noted-flask
    spec:
      containers:
      - image: docker.io/debuglachy/noted-flask-app:52cfaa1ee899913f73ab92537f0618a73147e4b0
        name: noted-flask
        ports:
        - containerPort: 8080
