name: CI

on:
  push:
    branches: [main]

jobs:
  call-docker-publish:
    permissions:
      contents: write
      packages: write
    uses: debuglachy/ops/.github/workflows/docker-publish.yaml@main
    with:
      image_name: 'noted-flask-app'
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

#  python-coverage:
#    uses: debuglachy/ops/.github/workflows/python-coverage.yaml@main
#    with:
#      src_folder: '.'
#  python-package:
#    uses: debuglachy/ops/.github/workflows/python-package.yaml@main
#    with:
#      python_version: '3.10'
