name: CI

on:
  push:
    branches: [main]

jobs:
  call-docker-publish:
    permissions:
      contents: write
      packages: write
    uses: debuglachy/ops/.github/workflows/docker-publish.yaml@main
    with:
      image_name: 'noted-flask-app'
      image_registry: 'ghcr.io'
  call-python-package:
    permissions:
      contents: write
      pull-requests: write
    uses: debuglachy/ops/.github/workflows/python-package.yaml@main
    with:
      python_version: '3.13'
      src_folder: '.'
