name: Python Coverage

on:
    pull_request:
        branches:
            - main

permissions:
    pull-requests: write

jobs:
    python-coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Set up Py
              uses: actions/setup-python@v4
              with:
                python-version: 3.13
            - name: Get dependencies
              run: |
                pip install -r requirements.txt
                pip install pytest
                pip install coverage
                pip install pytest-cov
            - name: Check coverage
              run: pytest --cov=src
            - name: Comment coverage
              uses: py-cov-action/python-coverage-comment-action@v3
              with:
                GITHUB_TOKEN: ${{ github.token }}
                MINIMUM_GREEN: 90
                MINIMUM_ORANGE: 70
            - name: Fail low coverage
              run: coverage report --fail-under=90
